# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
  build-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Test
      run: xcodebuild -scheme OSInfo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' clean build test

  build-maccatalyst:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Test
      run: xcodebuild -scheme OSInfo -sdk macosx -destination 'platform=macOS,variant=Mac Catalyst' clean build test

  build-linux:
  
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v